name: Unit tests
on:
  push:
    paths:
      - 'gulpfile.mjs'
      - 'src/**'
      - 'web/**'
      - 'test/test.mjs'
      - 'test/unit/**'
      - '.github/workflows/unit_tests.yml'
    branches:
      - master
  pull_request:
    paths:
      - 'gulpfile.mjs'
      - 'src/**'
      - 'web/**'
      - 'test/test.mjs'
      - 'test/unit/**'
      - '.github/workflows/unit_tests.yml'
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: read

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        node-version: [lts/*]
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Gulp
        run: npm install -g gulp-cli

      - name: Install other dependencies
        run: npm install

      - name: Run unit tests
        run: gulp unittest --bot --headless
